### ISSUE TITLE
Usage issue: RCTBottomSheetBehaviorAndroid.Commands

### ISSUE THREAD

**Issue by HZSamir** [cesardeazevedo/react-native-bottom-sheet-behavior#15]
Hello,
In a new project, when trying the basic example in the readme, something like:
```javascript
    return (
      <CoordinatorLayout style={styles.container}>
        <View style={{ flex: 1, backgroundColor: 'transparent' }}></View>
        <BottomSheetBehavior
            ref="bottomSheet"
            peekHeight={50}
            hideable={true}
            state={BottomSheetBehavior.STATE_COLLAPSED}>
            <View></View>
        </BottomSheetBehavior>
        <FloatingActionButton ref="fab" />
      </CoordinatorLayout>
    );
```

 I get the following error:
```
undefined is not an object (evaluating '_reactNative.UIManager.RCTBottomSheetBehaviorAndroid.Commands')
```

I have no idea where the issue is coming from.

**Comment by cesardeazevedo** [comment]
Hi, thanks for report, i will take a look.

which RN version are you using?
Did you tried the [example](https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior/tree/master/example)?

**Comment by HZSamir** [comment]
Hi,
I tried using both RN@0.40.0 and RN@0.37.0, both don't work.
As for the example it runs well.

**Comment by cesardeazevedo** [comment]
It seems that you didn't setup it correctly, did you follow the [manually installation?](https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior#install-manually) did you made the changes on the `MainApplication.java`, `android/app/build.gradle` and `android/settings.gradle`?

**Comment by HZSamir** [comment]
Hello again,
Indeed, I went wrong somewhere during the installation. Edited `android/build.gradle` instead of `android/app/build.gradle` Thank you.

**Comment by HZSamir** [comment]
I also noticed that your module is incompatible with RN@0.37.0. I was trying to use it in a Pepperoni boilerplate. Ultimately I had to manually upgrade my dependencies.
Again, thank you.

**Comment by cesardeazevedo** [comment]
Yes, indeed, the recent break changes on react-native has been impossible to support old RN versions, i hope Pepperoni boilerplate update their react-native [soon](https://github.com/futurice/pepperoni-app-kit/pull/170)
