### ISSUE TITLE
Replacing FloatingActionButton with Action Button

### ISSUE THREAD

**Issue by HZSamir** [cesardeazevedo/react-native-bottom-sheet-behavior#16]
Hello again, 
I would like to replace the FloatingActionButton in your example by this [component](https://github.com/mastermoo/react-native-action-button)

So in your example's code, in the `GoogleMapsView.js` file,  basically this:
```javascript
  renderFloatingActionButton = () => {
    const { bottomSheetColor } = this.state
    const isExpanded = bottomSheetColor === 1
    return (
      <FloatingActionButton
        ref={(floating) => { this.floating = floating }}
        elevation={18}
        rippleEffect={true}
        icon={'directions'}
        iconProvider={IconMDI}
        iconColor={!isExpanded ? WHITE : PRIMARY_COLOR}
        onPress={this.handleFabPress}
        backgroundColor={isExpanded ? WHITE : PRIMARY_COLOR}
      />
    )
  }
```

turned into this:
```javascript
  renderFloatingActionButton = () => {
    return (
      <ActionButton ref={(floating) => { this.floating = floating }} buttonColor="rgba(231,76,60,1)">
        <ActionButton.Item buttonColor='#9b59b6' title="New Task" onPress={() => console.log("notes tapped!")}>
          <Icon name="md-create" style={styles.actionButtonIcon} />
        </ActionButton.Item>
        <ActionButton.Item buttonColor='#3498db' title="Notifications" onPress={() => {}}>
          <Icon name="md-notifications-off" style={styles.actionButtonIcon} />
        </ActionButton.Item>
        <ActionButton.Item buttonColor='#1abc9c' title="All Tasks" onPress={() => {}}>
          <Icon name="md-done-all" style={styles.actionButtonIcon} />
        </ActionButton.Item>
      </ActionButton>
    )
  }
```

However, I get the following error: 
`undefined is not a function (evaluating this.floating.setAnchorId(this.bottomSheet))`

Is it at all possible to use this component as I intend, or is it meant only to be used with the `FloatingActionButton` component?

Thank you.

**Comment by cesardeazevedo** [comment]
No, you can't, FloatingActionButton is a completely [native component](https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior/blob/master/android/src/main/java/com/bottomsheetbehavior/FloatingActionButtonView.java), and react-native-action-button doesn't, they don't work together, and the `setAnchorId` is a internal function from `FloatingActionButton`, not react-native-action-button or something from react-native.

react-native-action-button intent to work as absolute position, and doesn't support anything further than that, such as relative parents.
