### ISSUE TITLE
state is not being updated

### ISSUE THREAD

**Issue by DanielMartini** [cesardeazevedo/react-native-bottom-sheet-behavior#22]
In v1.0.0-beta version the state "state" of the BottomSheetBehavior component never changes, everything works but it doesn't gets updated (always is null) so you cannot read in which state is the component

**Comment by cesardeazevedo** [comment]
Hi, thanks for the feedback.

What you mean with always null? Did you tried get the state on `onStateChange` function?

**Comment by DanielMartini** [comment]
Actually I tried to access the prop with a ref `this.bottomSheet.state`.

I looked the onStateChange function but I was expecting to recieve the state code not the event, how can I access to the current state of the component?

Thanks :)

**Comment by cesardeazevedo** [comment]
There's no such thing as `this.bottomSheet.state`, you can get the state code directly on the event as follows:

```
onStateChange(e) {
  this.lastState = e.nativeEvent.state
}
```

**Comment by DanielMartini** [comment]
Thank you for your fast response :)
