### ISSUE TITLE
Margin top if StatusBar is deleted or isn't translucent

### ISSUE THREAD

**Issue by DanielMartini** [cesardeazevedo/react-native-bottom-sheet-behavior#23]
This happens if you delete the StatusBar component or you delete the translucent prop (v1.0.0-beta)

![captura](https://cloud.githubusercontent.com/assets/8677856/25063194/1f4f75b0-21de-11e7-99d2-706e22052d8c.PNG)

**Comment by cesardeazevedo** [comment]
That's annoying indeed, but why you would delete the StatusBar?

**Comment by DanielMartini** [comment]
It keeps in another views of my app and bugs other sections with the transluced prop, the components go behind the status bar

![captura](https://cloud.githubusercontent.com/assets/8677856/25067215/c130a4e0-223c-11e7-991d-ee7a6f5104bb.PNG)

**Comment by cesardeazevedo** [comment]
Oh, i thought that you was setting StatusBar dynamically, my bad, this latest commit should fix it, and translucent status bar is disabled by default, and enable it should require the `translucent` prop on either `ScrollingAppBarLayout` or `MergedAppBarLayout`, which just adjusts the AppBar margins, and doesn't change anything on the translucent itself.
