### ISSUE TITLE
Possible to animate from STATE_COLLAPSED to STATE_EXPANDED?

### ISSUE THREAD

**Issue by RobCherry** [cesardeazevedo/react-native-bottom-sheet-behavior#25]
Is it possible to animate from `STATE_COLLAPSED` to `STATE_EXPANDED`?  Animating from `STATE_EXPANDED` to `STATE_COLLAPSED` seems to happen without needing to add anything special.  Also, are there any plans to make the animation durations configurable?

**Comment by cesardeazevedo** [comment]
Hi, take a look at this example to change states https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior/blob/master/example/views/AnchorSheetView.js#L48

Regarding the the durations configurable, this is a core component of [support design](https://developer.android.com/reference/android/support/design/widget/BottomSheetBehavior.html) which is truly native with a slight small changes to support the anchor state, i can't touch at anything more than that.

Tell me if you got it.

**Comment by cesardeazevedo** [comment]
That's been a while, so i'm going to close it.
