### ISSUE TITLE
Remove map example GoogleMapsView.js

### ISSUE THREAD

**Issue by Angelk90** [cesardeazevedo/react-native-bottom-sheet-behavior#30]
Hi, in the end to try the individual examples, I copied the code directly.

In the example: https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior/blob/master/example/views/GoogleMapsView.js

I would like to remove the map to use it as a profile page.
How can I do?
I would like to get something like this:
![screenshot_20170820-211450](https://user-images.githubusercontent.com/20476002/29497714-49ca2b0a-85ed-11e7-9535-cff11e243085.jpeg)

@cesardeazevedo: it's possible to do it?
I'm sorry if I disturb you.

**Comment by cesardeazevedo** [comment]
Sorry for didn't see this, but yes, the map is just an example to show the bottom sheet over it, the same as the google maps example.

It really depends on what you want to achieve, if you are unsure if you need this component, you might don't need that, you can easily copy the [GoogleMapsView.js (https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior/blob/master/example/views/GoogleMapsView.js) and use it without the bottom sheet as well with no problems.

I'm going to close this once i don't know how to help you further than that.
