### ISSUE TITLE
Minimum Android Version?

### ISSUE THREAD

**Issue by Noitidart** [cesardeazevedo/react-native-bottom-sheet-behavior#33]
Hi there,

I was wondering with the minimum Android version supported is? Especially for `BottomSheetBehavior`, because it is custom implementation, is it 4.1+ safe? I am trying to support minimum version RN supports which is 4.1.

Thanks for an awesome module and providing support to the many people posting in your issues forum.

**Comment by cesardeazevedo** [comment]
Should work as expected, expect a few props that are not available on API 16, such elevation shadows and [changing](https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior/blob/50e8344c2b3b2371f597bd1bfcb077631b73948e/android/src/main/java/com/bottomsheetbehavior/FloatingActionButtonView.java#L81-L83) the FAB Icon color when expanded and using BottomSheetHeader, (which there's may be a different approach to handle that on the native side).

here's a demo running on 4.1.1

![api16](https://user-images.githubusercontent.com/5366959/32993078-5d1ec622-cd3a-11e7-885e-f16c58cbda40.gif)

You can also notice the translucent status bar is not supported on API 16, so you will need to adapt a few things on the header to fits nicely.

**Comment by Noitidart** [comment]
Wow! Thank you sir very much for taking the time to even upload a screencast on 4.1.1! My sincerest gratitude!
