### ISSUE TITLE
call FAB's show/hide method cause 'undefined is not a object' error

### ISSUE THREAD

**Issue by coinicon72** [cesardeazevedo/react-native-bottom-sheet-behavior#37]
I think the root cause is at line 87 of FloatingActionButton.js:

UIManager.BSBFloatingActionButton.Commands[command],

should be:
UIManager.BSBFloatingActionButtonAndroid.Commands[command],

Thank for your great works!!

**Comment by cesardeazevedo** [comment]
Thanks for report, i pushed a fix at `1.0.0-beta.8`
