### ISSUE TITLE
Could not find a declaration file for module 'react-native-bottom-sheet-behavior'

### ISSUE THREAD

**Issue by SamaneYaghoubi** [cesardeazevedo/react-native-bottom-sheet-behavior#46]
while I added this component to my react-native project, the application screen turns to white empty page.
The import react-native-bottom-sheet-behavior line has '...' near the package name:
 
![screenshot_5](https://user-images.githubusercontent.com/22401814/47717278-9896ff00-dc5a-11e8-8e5d-4c2e02ea01d3.png)

and it has this message:
[ts]
Could not find a declaration file for module 'react-native-bottom-sheet-behavior'. '/project/node_modules/react-native-bottom-sheet-behavior/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-bottom-sheet-behavior` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-bottom-sheet-behavior';

`npm install @types/react-native-bottom-sheet-behavior` couldn't help, because this package doesn't exist in npm.

react: "16.6.0-alpha.8af6728"
react-native: "0.57.3"
react-native-bottom-sheet-behavior: "^1.0.0"

**Comment by cesardeazevedo** [comment]
Hi, i am not sure if understood your issue, but it seems like you are using typescript and your editor is complaining that didn't found any typings for this library, but those messages are not related to a white empty page.

I don't use typescript, so i have no plans and interest to support typescript typings at the moment.

If you could provide more information, i would be glad to help.
