### ISSUE TITLE
requireNativeComponent: "BSBBottomSheet-BehaviorAndroid" was not found in the UIManager.

### ISSUE THREAD

**Issue by SamaneYaghoubi** [cesardeazevedo/react-native-bottom-sheet-behavior#47]
I'm getting the following error when starting my App on Android (in Debug).

![screenshot_6](https://user-images.githubusercontent.com/22401814/47747389-84c0bc80-dc9d-11e8-8e95-97dcc4f32fe4.png)

react: "16.6.0-alpha.8af6728"
react-native: "0.57.4"

**Comment by cesardeazevedo** [comment]
This is a linking error, have you installed it correctly and did the linking process on `MainApplication.java`, `android/app/build.gradle`, `android/settings.gradle` respectively? and compiled it with `react-native run-android`?

https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior#install-manually

**Comment by SamaneYaghoubi** [comment]
I installed it with npm, Is it needed to do the linking process?

**Comment by cesardeazevedo** [comment]
Yes, you need to linking the library on the java side as the README says https://github.com/cesardeazevedo/react-native-bottom-sheet-behavior#install-manually
