### ISSUE TITLE
UIManager['BSBottomSheetBehaviourAndroid'] is no longer supported . Use UIManager.ViewManagerConfig('BSBottomSheetBehaviourAndroid') instead warning 

### ISSUE THREAD

**Issue by arunkrishnang86** [cesardeazevedo/react-native-bottom-sheet-behavior#48]
UIManager['BSBottomSheetBehaviourAndroid'] is no longer supported . Use UIManager.ViewManagerConfig('BSBottomSheetBehaviourAndroid') instead warning is giving in the simulator 

![image](https://user-images.githubusercontent.com/47097401/52699714-6ce71d00-2f9c-11e9-9775-14f731fd1485.png)

**Comment by arunkrishnang86** [comment]
Do any body have a solution for this?

**Comment by cesardeazevedo** [comment]
Hi, thanks for reporting, i am gonna take a look at this next week, since i am in vacation right now.

**Comment by chaitratc** [comment]
Any update on this issue?

**Comment by cesardeazevedo** [comment]
Sorry guys, i totally forgot, i am fixing it right now

**Comment by dimlksin2** [comment]
_reactNative.UIManager.getViewManagerConfig('BSBBottomSheetBehaviorAndroid')

**Comment by cesardeazevedo** [comment]
@dimlksin2 that was fixed at 6076b558cdc703d4e805b54881f7b129ecee6844
