### ISSUE TITLE
[Question] Header with zero height

### ISSUE THREAD

**Issue by Andreyco** [cesardeazevedo/react-native-bottom-sheet-behavior#8]
Is it possible to have Bottom Sheet with zero height (so that it does not occupy any space when "hidden") and control sheet completely remotely?

Dummy question, but sorry, I am from iOS world.

TY

**Comment by cesardeazevedo** [comment]
Did you tried the `hideable={true}` property together with `state={5}` (STATE_HIDDEN)? it would hidden the bottom sheet completely and not only collapsed.

**Comment by Andreyco** [comment]
Looks like it's related to my layout setup. Will review & close later. Thanks for heads up

**Comment by Andreyco** [comment]
Okay. There is visual glitch, coincidence, when bottom sheet looks like it occupies space, even when it should not. That's why I asked the original question.

The real issue is that inner content of "wrapper" is shrunk for unknown reason.

Please, see pictures below...
- outer wrapper with red border takes whole screen
- inner wrapper with green border is set to fit its parent with red border (but it does not)
- space under rectangle is exact space bottom sheet occupies when expanded

Examples adjusted to demonstrate the issue is here Andreyco/react-native-bottom-sheet-behavior@b409def7dabddc279fbfffaa3566db2988713538

![sheet-collapsed](https://cloud.githubusercontent.com/assets/829963/20611932/832c0692-b2b3-11e6-8898-985fd0fed4d7.png)
![sheet-expanded](https://cloud.githubusercontent.com/assets/829963/20611931/832abe4a-b2b3-11e6-82e1-5d6de785ca51.png)

**Comment by cesardeazevedo** [comment]
Thanks for report, i will take a look at it closely tomorrow, but i suspect a `flex` issue after a breaking changed on react-native 0.36.0

**Comment by cesardeazevedo** [comment]
Hi, sorry for the delayed.

I have tested your code, but i not fully understand your changes, but removing `flex: 1` from `container` and `innerFlexContainer` it's seems to work, i think they did some [changes on CSSLayout after 0.36.0](https://github.com/facebook/react-native/commit/0a9b6bedb312eba22c5bc11498b1cc41363e5f27) that you should be careful when using `flex: 1` and most of the time it will be unnecessary.

Tell me if you got it.

**Comment by Andreyco** [comment]
Confirmed, I messed the layout, looks so... Closing
